##
## see http://about.travis-ci.org/docs/user/languages/python/
##

language: python
python:
  - "2.7"

# command to install dependencies
install:
  - "make devel"

# command to run tests
script:
  - "make test"
  - "make bdist"
