##
## see http://about.travis-ci.org/docs/user/languages/python/
##

language: python
python:
  - "2.7"

# command to install dependencies
install:
  - "pip install --use-mirrors ."
  - "pip install --use-mirrors -e .[develop]"
  - "pip install --use-mirrors -r requirements.txt"

# command to run tests
script: python setup.py test
