##
## see http://about.travis-ci.org/docs/user/languages/python/
##

language: python
python:
  - "2.7"

# command to install dependencies
install:
  - "pip install --use-mirrors ."
  - "pip install --use-mirrors -r requirements.txt"

# we could add
# - "pip install --use-mirrors -e .[develop]"

# command to run tests
script:
  - "make test"
  - "make docs-web"
