#
# Candelabra
#
# Copyright Alvaro Saurin 2013 - All right Reserved
#
"""
Linux guest definition
"""

from logging import getLogger

from candelabra.base import Guest

logger = getLogger(__name__)

#: create a directory if it does not exist
MKDIR_COMMAND = "mkdir {directory}"
#: the command used for mounting a shared folder in a Linux machine
MOUNT_COMMAND = "mount -t {type} {mount_options} {directory} {mount_point}"
MOUNT_OPTIONS = "-o uid=`id -u {owner}`,gid=`getent group {group} | cut -d: -f3`"

#: the command used for shutting down a Linux machine
SHUTDOWN_COMMAND = "shutdown -h now"

#: command for getting the IP addresses
GET_IPS_COMMAND = "ifconfig  | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1 }'"

#: template for network device with DHCP
TEMPLATE_DHCP = """
#VAGRANT-BEGIN
# The contents below are automatically generated by Vagrant. Do not modify.
BOOTPROTO=dhcp
ONBOOT=yes
DEVICE=eth{iface}
#VAGRANT-END
"""

#: template for network device with static IP
TEMPLATE_STATIC = """
#VAGRANT-BEGIN
# The contents below are automatically generated by Vagrant. Do not modify.
BOOTPROTO=none
IPADDR={ip}
NETMASK={netmask}
DEVICE=eth{iface}
PEERDNS=no
#VAGRANT-END
"""


class LinuxGuest(Guest):
    """ A Linux guest
    """

    def mkdir(self, directory):
        """ Create a remote directory
        """
        mkdir_command = MKDIR_COMMAND.format(directory=directory).split(' ')
        return self.communicator.sudo(mkdir_command)

    def mount(self, directory, mount_point, type='vboxsf', owner='vagrant', group='vagrant'):
        """ Mount a directory on a mount point
        """
        logger.info('mounting %s', directory)
        mount_options = MOUNT_OPTIONS.format(owner=owner, group=group)
        mount_command = MOUNT_COMMAND.format(directory=directory, type=type, mount_point=mount_point,
                                             mount_options=mount_options).split(' ')
        return self.communicator.sudo(mount_command)

    def shutdown(self):
        """ Shutdown the machine
        """
        shutdown_command = SHUTDOWN_COMMAND.split(' ')
        return self.communicator.sudo(shutdown_command)

    def get_ips(self):
        """ Get the IP addresses
        """
        command = GET_IPS_COMMAND.split(' ')
        return self.communicator.sudo(command)

    def change_hostname(self, name):
        # Get the current hostname
        # if existing fqdn setup improperly, this returns just hostname
        old = ''
        COMMAND = "hostname -f"
        code, stdout, stderr = self.communicator.sudo(COMMAND)
        if len(stdout):
            old = stdout

        # this works even if they're not both fqdn
        old_1 = old.split('.')[0]
        name_1 = name.split('.')[0]
        if old_1 != name_1:
            # hosts should resemble:
            # 127.0.0.1   localhost host.fqdn.com host
            # 127.0.1.1   host.fqdn.com host

            COMMAND = """
            sed -i 's/.*$/{name_1}/' /etc/hostname
            sed -ri 's@^(([0-9]{1,3}\.){3}[0-9]{1,3})\\s+(localhost)\\b.*$@\\1\\t{name} {name_1} \\3@g' /etc/hosts
            sed -ri 's@^(([0-9]{1,3}\.){3}[0-9]{1,3})\\s+({old_1})\\b.*$@\\1\\t{name} {name_1}@g' /etc/hosts
            """

            if self.communicator.test("`lsb_release -c -s` = hardy"):
                # hostname.sh returns 1, so I grep for the right name in /etc/hostname just to have a 0 exitcode
                COMMAND += """
                /etc/init.d/hostname.sh start; grep '{name}' /etc/hostname
                """
            else:
                COMMAND += """
                service hostname start
                """

            COMMAND += """
            hostname --fqdn > /etc/mailname
            ifdown -a; ifup -a; ifup -a --allow=hotplug
            """

            self.communicator.sudo_lines(COMMAND, old_1=old_1, name=name, name_1=name_1)

    def setup_iface(self, number, type, ip='', netmask=''):
        """ Setup a network interface
        """
        logger.info('setting up network device num:%d', number)

        # Accumulate the configurations to add to the interfaces file as
        # well as what interfaces we're actually configuring since we use that
        # later.
        scripts_dir = '/etc/sysconfig/network-scripts'

        # Render and upload the network entry file to a deterministic
        # temporary location.

        if type == 'dhcp':
            content = TEMPLATE_DHCP.format(iface=number)
        elif type == 'static':
            content = TEMPLATE_STATIC.format(iface=number, ip=ip, netmask=netmask)
        else:
            assert False

        logger.debug('saving template to temporal file...')
        self.machine.communicator.write_file(content, "/tmp/vagrant-network-entry_{iface}".format(iface=number))

        # Remove any previous vagrant configuration in this network interface's
        # configuration files.
        COMMANDS = """
        touch {scripts_dir}/ifcfg-eth{iface}
        sed -e '/^#VAGRANT-BEGIN/,/^#VAGRANT-END/ d' {scripts_dir}/ifcfg-eth{iface} > /tmp/vagrant-ifcfg-eth{iface}
        cat /tmp/vagrant-ifcfg-eth{iface} > {scripts_dir}/ifcfg-eth{iface}
        rm -f /tmp/vagrant-ifcfg-eth{iface}
        /sbin/ifdown eth{iface} 2> /dev/null
        cat /tmp/vagrant-network-entry_{iface} >> {scripts_dir}/ifcfg-eth{iface}
        ARPCHECK=no /sbin/ifup eth{iface} 2> /dev/null
        rm -f /tmp/vagrant-network-entry_{iface}
        """
        self.machine.communicator.sudo_lines(COMMANDS, iface=number, scripts_dir=scripts_dir)

